<?php

use Hyva\Theme\ViewModel\SvgIcons;

$hyvaicons = $viewModels->require(SvgIcons::class);
?>

<script>
    function initSveaOrderComment() {
        return {
            isLoading: false,
            options: {
                commentFormSelector: '#svea-checkout-comment'
            },

            submitOrderComment() {
                const form = document.querySelector(this.options.commentFormSelector);

                if (!form) {
                    console.error('Comment form not found');
                    return;
                }

                const formData = new FormData(form); // To serialize form data
                const url = form.action;

                this.isLoading = true;

                fetch(url, {
                        method: 'POST',
                        body: formData,
                        headers: {
                            'X-Requested-With': 'XMLHttpRequest',
                        },
                        credentials: 'include',
                    })
                    .then(response => {
                        if (response.ok) {
                            return response.text();
                        } else {
                            throw new Error('Failed to submit order comment.');
                        }
                    })
                    .then(() => {
                        this.isLoading = false;

                        dispatchMessages([{
                            type: "success",
                            text: '<?= $escaper->escapeJs(__('Order comment saved successfully.')) ?>'
                        }], 2000);
                    })
                    .catch(error => {
                        console.error('Error submitting order comment:', error);
                        this.isLoading = false;
                    });
            }
        }
    }
</script>
<?php $hyvaCsp->registerInlineScript() ?>

<div id="svea_comment" class="svea-block w-full flex" x-data="initSveaOrderComment()">
    <?php $customerComment = $block->getQuote()->getCustomerNote(); ?>
    <form method="post" action="<?= $block->getCommentSubmitUrl(); ?>" id="svea-checkout-comment" class="w-full">
        <div class="svea-comment-title">
            <label class="text-ui-2 pb-3 mb-0" for="svea_order_comment_textarea"><?= __('Order comments (optional)') ?></label>
        </div>
        <div class="fieldset comment">
            <div class="input-box field !pb-2">
                <textarea rows="10" value="" name="svea_customer_comment" id="svea_order_comment_textarea" placeholder="<?= __('Enter a comment for this order'); ?>"
                    class="svea-show-on-focus input-text w-full min-h-[104px] bg-transparent"><?= $customerComment; ?></textarea>
            </div>
            <div class="actions-toolbar">
                <div class="primary">
                    <button id="svea-submit" type="submit"
                        class="action apply svea-button btn btn-primary"
                        @click.prevent="submitOrderComment()"><?= __('Save'); ?></button>
                </div>
            </div>
        </div>
    </form>
    <div class="flex flex-row justify-center items-center w-full h-full fixed select-none z-50"
        style="left: 50%;top: 50%;transform: translateX(-50%) translateY(-50%);background: rgba(255,255,255,0.7);"
        x-show="isLoading"
        x-cloak
        x-transition:enter="ease-out duration-200"
        x-transition:enter-start="opacity-0"
        x-transition:enter-end="opacity-100"
        x-transition:leave="ease-in duration-200"
        x-transition:leave-start="opacity-100"
        x-transition:leave-end="opacity-0">
        <div class="lds-spinner">
            <div></div>
            <div></div>
            <div></div>
            <div></div>
            <div></div>
            <div></div>
            <div></div>
            <div></div>
            <div></div>
            <div></div>
            <div></div>
            <div></div>
        </div>
    </div>
</div>