<?php

// @codingStandardsIgnoreFile
?>
<div id="svea-checkout_giftcard" class="svea-checkout-block giftcard">
    <div class="svea-checkout-title" data-role="title">
        <h4 id="svea-checkout-review-heading" role="heading" aria-level="2">
            <?php echo $block->escapeHtml(__('Giftcard Code')) ?>
        </h4>
    </div>
    <form id="giftcard-coupon-form"
          action="<?php /* @escapeNotVerified */
          echo $block->getGiftcardSubmitUrl() ?>"
          method="post"
    >
        <div class="fieldset coupon">
            <input type="hidden" name="remove" id="remove-giftcard"/>
            <div class="field">
                <div class="control">
                    <input type="text" class="svea-checkout-show-on-focus input-text" id="giftcard_code"
                           name="giftcard_code"
                           placeholder="<?php echo $block->escapeHtml(__('Enter discount code')); ?>"/>
                </div>
            </div>
            <div class="actions-toolbar">
                <div class="primary">
                    <button class="action apply primary" type="submit" value="<?php /* @escapeNotVerified */
                    echo __('Apply Discount') ?>">
                        <span><?php /* @escapeNotVerified */
                            echo __('Apply Discount') ?></span>
                    </button>
                </div>
            </div>
        </div>
    </form>
</div>
