<?php

use Magento\Framework\Escaper;
use Hyva\Theme\ViewModel\HeroiconsSolid;

/** @var \Magento\Checkout\Block\Cart\Item\Renderer $block  */
/** @var \Magento\Quote\Model\Quote\Item $_item */
/** @var Escaper $escaper */

$_item = $block->getItem();
$product = $_item->getProduct();
$helper = $this->helper('\Svea\Checkout\Helper\Cart');
$qtyIncrements = floatval($_item->getData('qty_increments')) ? $_item->getData('qty_increments') : 1;
$heroIcons = $viewModels->require(HeroiconsSolid::class);
?>

<tr class="border-t border-primary last:border-b max-lg:flex flex-wrap w-full">
    <td class="svea-checkout-col item-img py-4 max-lg:w-full">
        <div class="flex gap-4">
            <div class="product-item-image">
                <?php if ($block->hasProductUrl()): ?>
                    <a href="<?= /* @escapeNotVerified */ $block->getProductUrl() ?>"> <?= $block->getImage($block->getProductForThumbnail(), 'svea_checkout_product_thumbnail')->toHtml() ?></a>
                <?php else: ?>
                    <?= $block->getImage($block->getProductForThumbnail(), 'svea_checkout_product_thumbnail')->toHtml() ?>
                <?php endif; ?>
            </div>
        </div>
    </td>
    <td class="svea-checkout-col item-desc">
        <div class="product-item-details w-full">
            <div class="product-item-info max-lg:h-full max-lg:flex max-lg:flex-col justify-between">
                <div>
                    <?php if ($block->hasProductUrl()): ?>
                        <a href="<?= /* @escapeNotVerified */ $block->getProductUrl() ?>"><strong class="product name product-item-name"><?php echo $escaper->escapeHtml($block->getProductName()) ?></strong></a>
                    <?php else: ?>
                        <?= $escaper->escapeHtml($block->getProductName()) ?>
                    <?php endif; ?>
                    <?php if ($product->getShortDescription()): ?>
                        <span class="product description product-item-description block w-full">
                            <?= /* @escapeNotVerified */
                            strip_tags($product->getShortDescription()) ?>
                        </span>
                    <?php endif; ?>
                    <?php if ($_options = $block->getOptionList()): ?>
                        <dl class="item-options">
                            <?php foreach ($_options as $_option) : ?>
                                <?php $_formatedOptionValue = $block->getFormatedOptionValue($_option) ?>
                                <dt><?php echo $block->escapeHtml($_option['label']) ?></dt>
                                <dd>
                                    <?php if (isset($_formatedOptionValue['full_view'])): ?>
                                        <?php /* @escapeNotVerified */
                                        echo $_formatedOptionValue['full_view'] ?>
                                    <?php else: ?>
                                        <?php /* @escapeNotVerified */
                                        echo $_formatedOptionValue['value'] ?>
                                    <?php endif; ?>
                                </dd>
                            <?php endforeach; ?>
                        </dl>
                    <?php endif; ?>
                    <?php if ($addtInfoBlock = $block->getProductAdditionalInformationBlock()): ?>
                        <?= $addtInfoBlock->setItem($_item)->toHtml() ?>
                    <?php endif; ?>
                </div>
            </div>
        </div>
    </td>
    <td class="svea-checkout-col qty pl-4 py-4 align-top" data-th="<?= $escaper->escapeHtml(__('Qty')); ?>">
        <?php
        $FormKey = $helper->getFormKey();
        ?>
        <div class="qty" data-th="<?= $escaper->escapeHtml(__('Qty')); ?>">
            <span class="qty">
                <label class="sr-only" for="cart-<?= $_item->getId() ?>-qty">
                    <?= $escaper->escapeHtml(__('Qty')) ?>
                </label>
                <span class="input-number-decrement cursor-pointer"
                    @click="updateItemQty(<?= $_item->getId() ?>, <?= $_item->getQty() - 1 ?>)">
                    <?= $heroIcons->minusHtml('', 12, 12); ?>
                </span>
                <input id="cart-<?= $_item->getId() ?>-qty"
                    name="cart[<?= $_item->getId() ?>][qty]"
                    data-cart-item-id="<?= $_item->getSku() ?>"
                    data-cart-product-id="<?= $_item->getId() ?>"
                    data-cart-form-key="<?= $FormKey->getFormKey(); ?>"
                    value="<?= $_item->getQty() ?>"
                    type="number"
                    min="1"
                    size="4"
                    title="<?= $escaper->escapeHtml(__('Qty')); ?>"
                    class="input-text qty ajax-qty-change"
                    maxlength="12"
                    data-validate="{required:true,'validate-greater-than-zero':true}"
                    data-role="cart-item-qty"
                    data-qty-increments="<?= $escaper->escapeHtmlAttr($qtyIncrements) ?>"
                    @change="updateItemQty(<?= $_item->getId() ?>, $event.target.value)" />

                <span class="input-number-increment cursor-pointer"
                    @click="updateItemQty(<?= $_item->getId() ?>, <?= $_item->getQty() + 1 ?>)">
                    <?= $heroIcons->plusHtml('', 12, 12); ?>
                </span>
            </span>
        </div>
    </td>

    <td class="svea-checkout-col price" data-th="<?php echo $escaper->escapeHtml(__('Price')); ?>">
        <span class="price-including-tax" data-label="<?php echo $escaper->escapeHtml(__('Price')); ?>">
            <?php echo $block->getUnitPriceHtml($_item); ?>
        </span>
    </td>

    <td class="svea-checkout-col subtotal" data-th="<?php echo $escaper->escapeHtml(__('Subtotal')); ?>">
        <?php if ($this->helper('Magento\Tax\Helper\Data')->displayCartPriceInclTax() || $this->helper('Magento\Tax\Helper\Data')->displayCartBothPrices()): ?>
            <span class="price-including-tax" data-label="<?php echo $escaper->escapeHtml(__('Incl. Tax')); ?>">
                <?php echo $block->getRowTotalInclTaxHtml($_item); ?>
            </span>
        <?php endif; ?>
        <?php if ($this->helper('Magento\Tax\Helper\Data')->displayCartPriceExclTax() || $this->helper('Magento\Tax\Helper\Data')->displayCartBothPrices()): ?>
            <span class="price-excluding-tax" data-label="<?php echo $escaper->escapeHtml(__('Excl. Tax')); ?>">
                <?php echo $block->getRowTotalExclTaxHtml($_item); ?>
            </span>
        <?php endif; ?>
        <span class="remove-product" @click="deleteItemFromCart(<?= $_item->getId() ?>)"><span><?= __('Remove') ?></span></span>
    </td>
</tr>