<?php

/** @var $block \Svea\Checkout\Block\Checkout */

//id  #svea-checkout_shipping_method is mandatory
?>
<div id="svea-checkout_shipping_method">
    <fieldset class="shipping-method-holder">
        <legend class="sr-only">
            <?= __('Shipping Method') ?>
        </legend>
        <?php if ($groups = $block->getShippingRateGroups()): ?>
            <?php $currentRate = $block->getCurrentShippingRate(); ?>
            <?php foreach ($groups as $code => $rates): ?>
                <?php if (0): ?><strong><?php echo $block->escapeHtml($block->getCarrierName($code)) ?></strong><?php endif; ?>
                <?php foreach ($rates as $rate):
                    $value = $block->escapeHtml($block->renderShippingRateValue($rate));
                    $checked = $currentRate === $rate->getCode() ? 'checked' : '';
                ?>
                    <div class="svea-checkout-radio-row">
                        <input type="radio"
                            name="shipping_method" <?php echo $checked; ?> value="<?php echo $value; ?>"
                            id="<?php echo $value; ?>"
                            @change="submitShippingMethodAjax" />
                        <label for="<?php echo $value; ?>" class="relative">
                            <?= $block->renderShippingRateOption($rate); ?>
                        </label>
                    </div>
                <?php endforeach; ?>
            <?php endforeach; ?>

        <?php else: ?>
            <p>
                <strong>
                    <?php echo $block->escapeHtml(__('Sorry, no quotes are available for this order right now.')); ?>
                </strong>
            </p>
        <?php endif; ?>
    </fieldset>
</div>